<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

return new class extends Migration
{
    /**
     * Catalogo de profesiones solicitado para el formulario publico de negociacion.
     *
     * Se reutiliza la tabla professions que ya usa Academic (id smallint sin
     * autoincremento, description unica). Los textos que ya existan se saltan
     * comparando normalizado (sin mayusculas ni espacios sobrantes), asi que la
     * migracion puede reejecutarse sin duplicar filas.
     *
     * Orden y contenido tomados del listado entregado; los duplicados internos
     * del listado se descartan aqui (se conserva la primera aparicion).
     */
    private const DESCRIPTIONS = [
        'Técnico en Administración',
        'Técnico en Administración de Empresas',
        'Técnico en Administración Pública',
        'Técnico en Almacenes',
        'Técnico en Asistencia Legal',
        'Técnico en Banca',
        'Técnico en Comercio Exterior',
        'Técnico en Compras',
        'Técnico en Contabilidad',
        'Técnico en Finanzas',
        'Técnico en Gestión de Proyectos',
        'Técnico en Gestión Documental',
        'Técnico en Gestión Empresarial',
        'Técnico en Logística',
        'Técnico en Marketing',
        'Técnico en Negocios Internacionales',
        'Técnico en Recursos Humanos',
        'Técnico en Seguros',
        'Técnico en Tributación',
        'Técnico en Ventas',
        'Técnico Jurídico',
        'Acuicultura',
        'Agricultura de Precisión',
        'Agroecología',
        'Agroindustria',
        'Agronomía',
        'Ciencia Animal',
        'Ciencia de los Alimentos',
        'Ciencia del Suelo',
        'Ciencias Agrarias',
        'Ciencias Forestales',
        'Conservación de Bosques',
        'Economía Agraria',
        'Extensión Agraria',
        'Fitotecnia',
        'Horticultura',
        'Ingeniería Agroindustrial',
        'Ingeniería Agronómica',
        'Ingeniería Forestal',
        'Ingeniería Pesquera',
        'Manejo Forestal',
        'Medicina Veterinaria',
        'Producción Agropecuaria',
        'Producción Animal',
        'Silvicultura',
        'Tecnología de Alimentos',
        'Veterinaria',
        'Zootecnia',
        'Técnico Agropecuario',
        'Técnico Agrícola',
        'Técnico en Acuicultura',
        'Técnico en Agricultura de Precisión',
        'Técnico en Agroecología',
        'Técnico en Agroindustria',
        'Técnico en Agronegocios',
        'Técnico en Conservación de Recursos Naturales',
        'Técnico en Enfermería Veterinaria',
        'Técnico en Horticultura',
        'Técnico en Manejo de Bosques',
        'Técnico en Procesamiento Pesquero',
        'Técnico en Producción Agrícola',
        'Técnico en Producción Animal',
        'Técnico en Riego',
        'Técnico en Silvicultura',
        'Técnico en Suelos',
        'Técnico en Viveros',
        'Técnico en Zootecnia',
        'Técnico Forestal',
        'Técnico Pecuario',
        'Técnico Pesquero',
        'Técnico Veterinario',
        'Técnico en Animación Digital',
        'Técnico en Artes Gráficas',
        'Técnico en Conservación y Restauración',
        'Técnico en Diseño de Interiores',
        'Técnico en Diseño de Modas',
        'Técnico en Diseño Gráfico',
        'Técnico en Fotografía',
        'Técnico en Ilustración',
        'Técnico en Producción Audiovisual',
        'Técnico en Producción Musical',
        'Técnico en Sonido',
        'Técnico en Teatro',
        'Animación',
        'Antropología',
        'Architecture',
        'Arqueología',
        'Arquitectura',
        'Arte Digital',
        'Artes Plásticas',
        'Artes Visuales',
        'Bellas Artes',
        'Cinematografía',
        'Composición Musical',
        'Conservación y Restauración',
        'Danza',
        'Diseño de Interiores',
        'Diseño de Modas',
        'Diseño de Producto',
        'Diseño Gráfico',
        'Diseño Industrial',
        'Estudios Clásicos',
        'Estudios Culturales',
        'Estudios de Género',
        'Filología',
        'Filosofía',
        'Fotografía',
        'Gestión Cultural',
        'Historia',
        'Historia del Arte',
        'Ilustración',
        'Lenguas Modernas',
        'Lingüística',
        'Literatura',
        'Musicología',
        'Música',
        'Patrimonio Cultural',
        'Religiones Comparadas',
        'Teatro',
        'Traducción e Interpretación',
        'Astrofísica',
        'Astronomía',
        'Biological Sciences',
        'Biología',
        'Biología Marina',
        'Biología Molecular',
        'Bioquímica',
        'Biotecnología',
        'Botánica',
        'Chemistry',
        'Ciencia de Datos',
        'Ciencias Ambientales',
        'Ciencias de la Tierra',
        'Ciencias del Mar',
        'Ecología',
        'Estadística',
        'Física',
        'Física Aplicada',
        'Genética',
        'Geofísica',
        'Geología',
        'Matemática Aplicada',
        'Matemáticas',
        'Mathematics',
        'Meteorología',
        'Microbiología',
        'Nanotecnología',
        'Oceanografía',
        'Paleontología',
        'Physics',
        'Química',
        'Química Farmacéutica',
        'Química Industrial',
        'Zoología',
        'Técnico en Análisis Químico',
        'Técnico en Control de Calidad',
        'Técnico en Estadística',
        'Técnico en Geología',
        'Técnico en Gestión Ambiental',
        'Técnico en Laboratorio',
        'Técnico en Laboratorio Biológico',
        'Técnico en Laboratorio Químico',
        'Técnico en Medio Ambiente',
        'Técnico en Meteorología',
        'Técnico en Topografía',
        'Archivística',
        'Bibliotecología',
        'Ciencia Política',
        'Ciencias de la Familia',
        'Ciencias de la Información',
        'Comunicación',
        'Criminalística',
        'Criminología',
        'Demografía',
        'Desarrollo Internacional',
        'Desarrollo Social',
        'Economía Social',
        'Estudios de Paz y Conflictos',
        'Estudios Urbanos',
        'Geografía',
        'Gerontología Social',
        'Periodismo',
        'Psicología',
        'Psychology',
        'Publicidad',
        'Relaciones Internacionales',
        'Relaciones Públicas',
        'Seguridad y Defensa',
        'Sociología',
        'Trabajo Social',
        'Técnico en Archivística',
        'Técnico en Bibliotecología',
        'Técnico en Comunicación Audiovisual',
        'Técnico en Criminalística',
        'Técnico en Periodismo',
        'Técnico en Producción de Medios',
        'Técnico en Relaciones Públicas',
        'Técnico en Seguridad Ciudadana',
        'Técnico en Trabajo Social',
        'Técnico en Auxiliar de Educación',
        'Técnico en Educación Especial',
        'Técnico en Educación Física',
        'Técnico en Educación Inicial',
        'Técnico en Educación Primaria',
        'Administración Educativa',
        'Ciencias de la Educación',
        'Diseño Curricular',
        'Educación Artística',
        'Educación de Adultos',
        'Educación en Ciencias Naturales',
        'Educación en Lenguas Extranjeras',
        'Educación Especial',
        'Educación Física',
        'Educación Inicial',
        'Educación Intercultural Bilingüe',
        'Educación Matemática',
        'Educación Musical',
        'Educación Primaria',
        'Educación Religiosa',
        'Educación Secundaria',
        'Educación Tecnológica',
        'Gestión Educativa',
        'Orientación Educativa',
        'Pedagogía',
        'Psicopedagogía',
        'Tecnología Educativa',
        'Arquitectura del Paisaje',
        'Construcción',
        'Diseño Urbano',
        'Edificación',
        'Ingeniería Aeroespacial',
        'Ingeniería Aeronáutica',
        'Ingeniería Agrícola',
        'Ingeniería Ambiental',
        'Ingeniería Automotriz',
        'Ingeniería Biomédica',
        'Ingeniería Civil',
        'Ingeniería de Alimentos',
        'Ingeniería de Gas',
        'Ingeniería de Mantenimiento',
        'Ingeniería de Manufactura',
        'Ingeniería de Materiales',
        'Ingeniería de Minas',
        'Ingeniería de Petróleo',
        'Ingeniería de Procesos',
        'Ingeniería de Producción',
        'Ingeniería de Recursos Hídricos',
        'Ingeniería de Seguridad',
        'Ingeniería de Transportes',
        'Ingeniería Electrónica',
        'Ingeniería Eléctrica',
        'Ingeniería en Telecomunicaciones',
        'Ingeniería Energética',
        'Ingeniería Estructural',
        'Ingeniería Ferroviaria',
        'Ingeniería Geomática',
        'Ingeniería Geotécnica',
        'Ingeniería Hidráulica',
        'Ingeniería Industrial',
        'Ingeniería Marítima',
        'Ingeniería Mecatrónica',
        'Ingeniería Mecánica',
        'Ingeniería Metalúrgica',
        'Ingeniería Naval',
        'Ingeniería Nuclear',
        'Ingeniería Petroquímica',
        'Ingeniería Química',
        'Ingeniería Sanitaria',
        'Ingeniería Topográfica',
        'Ingeniería Vial',
        'Urbanismo',
        'Técnico Aeronáutico',
        'Técnico Automotriz de Diagnóstico Electrónico',
        'Técnico Electricista',
        'Técnico Electrónico',
        'Técnico en Alimentos',
        'Técnico en Automatización Industrial',
        'Técnico en Calidad Industrial',
        'Técnico en CNC',
        'Técnico en Confecciones',
        'Técnico en Construcción Civil',
        'Técnico en Control Industrial',
        'Técnico en Dibujo Técnico',
        'Técnico en Diseño CAD',
        'Técnico en Edificaciones',
        'Técnico en Energía Eléctrica',
        'Técnico en Energías Renovables',
        'Técnico en Geomática',
        'Técnico en Instalaciones Eléctricas',
        'Técnico en Instalaciones Sanitarias',
        'Técnico en Instrumentación Industrial',
        'Técnico en Mantenimiento Aeronáutico',
        'Técnico en Mantenimiento Electromecánico',
        'Técnico en Mantenimiento Industrial',
        'Técnico en Manufactura',
        'Técnico en Mecatrónica',
        'Técnico en Mecánica Automotriz',
        'Técnico en Mecánica Industrial',
        'Técnico en Metalurgia',
        'Técnico en Minería',
        'Técnico en Obras Viales',
        'Técnico en Petroquímica',
        'Técnico en Petróleo y Gas',
        'Técnico en Procesamiento de Minerales',
        'Técnico en Procesos Industriales',
        'Técnico en Producción Industrial',
        'Técnico en Química Industrial',
        'Técnico en Refrigeración y Climatización',
        'Técnico en Seguridad Industrial',
        'Técnico en Soldadura',
        'Técnico en Tecnología de Alimentos',
        'Técnico Naval',
        'Técnico Textil',
        'Derecho Administrativo',
        'Derecho Comercial',
        'Derecho de Familia',
        'Derecho Internacional Privado',
        'Derecho Internacional Público',
        'Derecho Procesal',
        'Gestión Comercial',
        'Gestión de Emprendimiento',
        'Gestión de Innovación',
        'Gestión de Operaciones',
        'Gestión Estratégica',
        'Accounting',
        'Actuaría',
        'Administración de Empresas',
        'Administración de Negocios Internacionales',
        'Administración Financiera',
        'Administración Pública',
        'Administración y Dirección de Empresas',
        'Auditoría',
        'Banca y Finanzas',
        'Business Administration',
        'Ciencias Jurídicas',
        'Comercio Exterior',
        'Contabilidad',
        'Contaduría Pública',
        'Derecho',
        'Derecho Ambiental',
        'Derecho Civil',
        'Derecho Constitucional',
        'Derecho Corporativo',
        'Derecho Digital',
        'Derecho Empresarial',
        'Derecho Internacional',
        'Derecho Laboral',
        'Derecho Penal',
        'Derecho Tributario',
        'Economics',
        'Economía',
        'Economía Aplicada',
        'Emprendimiento',
        'Finanzas',
        'Gestión de la Cadena de Suministro',
        'Gestión de la Calidad',
        'Gestión de Marketing',
        'Gestión de Proyectos',
        'Gestión de Recursos Humanos',
        'Gestión del Talento',
        'Gestión Empresarial',
        'Gestión Tributaria',
        'Law',
        'Logística',
        'Marketing',
        'Marketing Digital',
        'Mercadotecnia',
        'Negocios Internacionales',
        'Notariado y Registro',
        'Propiedad Intelectual',
        'Seguros',
        'Supply Chain Management',
        'Anestesiología',
        'Cardiología',
        'Cirugía General',
        'Dermatología',
        'Endocrinología',
        'Gastroenterología',
        'Geriatría',
        'Hematología',
        'Infectología',
        'Medicina de Emergencias',
        'Medicina Familiar',
        'Medicina Interna',
        'Neurología',
        'Oftalmología',
        'Oncología',
        'Pediatría',
        'Psiquiatría',
        'Traumatología y Ortopedia',
        'Urología',
        'Administración en Salud',
        'Anatomía Patológica',
        'Audiología',
        'Ciencias Biomédicas',
        'Ciencias de la Salud',
        'Dental Medicine',
        'Dentistry',
        'Dietética',
        'Enfermería',
        'Epidemiología',
        'Estomatología',
        'Farmacia',
        'Fisioterapia',
        'Fonoaudiología',
        'Genética Médica',
        'Gerontología',
        'Gestión de Servicios de Salud',
        'Imagenología',
        'Laboratorio Clínico',
        'Logopedia',
        'Medicina',
        'Medicina General',
        'Medicina Humana',
        'Medicina Tradicional y Complementaria',
        'Medicine',
        'Nursing',
        'Nutrición',
        'Obstetricia',
        'Odontología',
        'Optometría',
        'Podología',
        'Psicología Clínica',
        'Radiología',
        'Radioterapia',
        'Rehabilitación',
        'Salud Ambiental',
        'Salud Ocupacional',
        'Salud Pública',
        'Tecnología Médica',
        'Terapia del Lenguaje',
        'Terapia Física',
        'Terapia Ocupacional',
        'Óptica',
        'Técnico Dental',
        'Técnico en Anatomía Patológica',
        'Técnico en Atención Prehospitalaria',
        'Técnico en Audiología',
        'Técnico en Emergencias Médicas',
        'Técnico en Enfermería',
        'Técnico en Enfermería Técnica',
        'Técnico en Farmacia',
        'Técnico en Fisioterapia',
        'Técnico en Hemoterapia',
        'Técnico en Higiene Dental',
        'Técnico en Histología',
        'Técnico en Imagenología',
        'Técnico en Instrumentación Quirúrgica',
        'Técnico en Laboratorio Clínico',
        'Técnico en Nutrición',
        'Técnico en Odontología',
        'Técnico en Podología',
        'Técnico en Prótesis Dental',
        'Técnico en Radiología',
        'Técnico en Radioterapia',
        'Técnico en Rehabilitación',
        'Técnico en Salud Ocupacional',
        'Técnico en Salud Pública',
        'Técnico en Terapia Ocupacional',
        'Técnico en Óptica y Optometría',
        'Técnico Paramédico',
        'Técnico Deportivo',
        'Técnico en Agencias de Viajes',
        'Técnico en Bartender y Coctelería',
        'Técnico en Cocina',
        'Técnico en Defensa Civil',
        'Técnico en Entrenamiento Deportivo',
        'Técnico en Gastronomía',
        'Técnico en Gestión de Riesgos',
        'Técnico en Gestión Hotelera',
        'Técnico en Guía de Turismo',
        'Técnico en Hotelería',
        'Técnico en Mantenimiento de Aeronaves',
        'Técnico en Operaciones Aeroportuarias',
        'Técnico en Operaciones Portuarias',
        'Técnico en Organización de Eventos',
        'Técnico en Panadería',
        'Técnico en Pastelería',
        'Técnico en Prevención de Riesgos',
        'Técnico en Recreación',
        'Técnico en Seguridad',
        'Técnico en Seguridad Privada',
        'Técnico en Seguridad y Salud en el Trabajo',
        'Técnico en Transporte',
        'Técnico en Turismo',
        'Administración Hotelera',
        'Artes Culinarias',
        'Aviación Comercial',
        'Ciencias del Deporte',
        'Culinary Arts',
        'Deportes',
        'Educación Física y Deporte',
        'Gastronomía',
        'Gestión Aeroportuaria',
        'Gestión de Emergencias',
        'Gestión de Eventos',
        'Gestión de Riesgos y Desastres',
        'Gestión Portuaria',
        'Gestión Turística',
        'Higiene Ocupacional',
        'Hotelería',
        'Náutica',
        'Prevención de Riesgos Laborales',
        'Protección Civil',
        'Recreación',
        'Seguridad Industrial',
        'Seguridad Integral',
        'Servicios Comunitarios',
        'Tourism Management',
        'Transporte y Logística',
        'Turismo',
        'Computación Gráfica',
        'Computación Paralela',
        'Computación Teórica',
        'Desarrollo de Aplicaciones',
        'Ingeniería de Calidad de Software',
        'Ingeniería de Software Empresarial',
        'Sistemas Distribuidos',
        'Visión por Computador',
        'Analítica de Datos',
        'Arquitectura de Software',
        'Bioinformática',
        'Ciberseguridad',
        'Ciencias de la Computación',
        'Computación',
        'Computación en la Nube',
        'Desarrollo de Software',
        'Desarrollo de Videojuegos',
        'DevOps',
        'Informática',
        'Informática Biomédica',
        'Ingeniería de Computación',
        'Ingeniería de Datos',
        'Ingeniería de Sistemas',
        'Ingeniería de Sistemas de Información',
        'Ingeniería de Software',
        'Ingeniería de Telecomunicaciones',
        'Ingeniería en Desarrollo de Software',
        'Ingeniería Informática',
        'Ingeniería Telemática',
        'Ingeniería Web',
        'Inteligencia Artificial',
        'Interacción Humano-Computadora',
        'Realidad Virtual y Aumentada',
        'Redes y Telecomunicaciones',
        'Robótica',
        'Seguridad Informática',
        'Sistemas de Información',
        'Sistemas Embebidos',
        'Software Engineering',
        'Systems Engineering',
        'Tecnologías de la Información',
        'Técnico en 3D y Modelado Digital',
        'Técnico en Aplicaciones Móviles',
        'Técnico en Automatización',
        'Técnico en Base de Datos',
        'Técnico en Ciberseguridad',
        'Técnico en Ciencia de Datos',
        'Técnico en Computación',
        'Técnico en Computación en la Nube',
        'Técnico en Desarrollo de Software',
        'Técnico en Desarrollo Web',
        'Técnico en Electrónica Digital',
        'Técnico en Informática',
        'Técnico en Inteligencia Artificial',
        'Técnico en Multimedia',
        'Técnico en Programación',
        'Técnico en Redes',
        'Técnico en Robótica',
        'Técnico en Seguridad Informática',
        'Técnico en Sistemas',
        'Técnico en Sistemas Embebidos',
        'Técnico en Soporte Informático',
        'Técnico en Telecomunicaciones',
        'Técnico en Videojuegos',
    ];

    /**
     * Codigos reservados del catalogo original ("Sin especificar" = 998,
     * "Otros" = 999). Las profesiones nuevas se numeran por debajo de este limite.
     */
    private const RESERVED_FROM = 998;

    /**
     * Textos del catalogo original que coinciden (normalizados) con el listado
     * entregado. up() los salta por findId(); down() no debe borrarlos porque no
     * los creo esta migracion.
     */
    private const PREEXISTING = [
        'Ingeniería de sistemas',
        'Ingeniería industrial',
        'Ingeniería civil',
        'Ingeniería electrónica',
        'Ingeniería mecánica',
        'Ingeniería ambiental',
        'Medicina',
        'Enfermería',
        'Odontología',
        'Contabilidad',
        'Derecho',
        'Psicología',
        'Administración de empresas',
        'Economía',
        'Arquitectura',
        'Educación',
        'Comunicación',
        'Periodismo',
        'Diseño gráfico',
        'Trabajo social',
        'Filosofía',
        'Sociología',
        'Relaciones internacionales',
        'Ciencias políticas',
        'Biología',
        'Química',
        'Física',
        'Matemáticas',
    ];

    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // professions.id es smallint sin autoincremento: los ids se asignan a
        // mano, continuando despues del ultimo id real del catalogo.
        $nextId = (int) DB::table('professions')
            ->where('id', '<', self::RESERVED_FROM)
            ->max('id');

        foreach (self::DESCRIPTIONS as $description) {
            if ($this->findId($description)) {
                continue;
            }

            // Defensivo: si el id calculado ya esta ocupado (catalogo ampliado a
            // mano entre migraciones), se busca el primero libre.
            do {
                $nextId++;
            } while (DB::table('professions')->where('id', $nextId)->exists());

            DB::table('professions')->insert([
                'id' => $nextId,
                'description' => $description,
            ]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Solo se quitan las filas que agrego esta migracion y que nadie usa en
        // people.profession_id; las que ya existian con ese mismo texto se
        // conservan.
        $preexisting = array_map(fn ($d) => Str::lower(trim($d)), self::PREEXISTING);

        foreach (self::DESCRIPTIONS as $description) {
            if (in_array(Str::lower(trim($description)), $preexisting, true)) {
                continue;
            }

            $id = $this->findId($description);

            if (! $id || DB::table('people')->where('profession_id', $id)->exists()) {
                continue;
            }

            DB::table('professions')->where('id', $id)->delete();
        }
    }

    /**
     * Id de la profesion por descripcion, ignorando mayusculas y espacios.
     *
     * El catalogo original guarda algunas descripciones con distinta
     * capitalizacion, asi que la comparacion normalizada evita duplicar una
     * profesion que ya existe escrita de otra forma.
     */
    private function findId(string $description): ?int
    {
        $id = DB::table('professions')
            ->whereRaw('LOWER(TRIM(description)) = ?', [Str::lower(trim($description))])
            ->value('id');

        return $id === null ? null : (int) $id;
    }
};
